from pydantic import BaseModel,Field
from typing import List,Dict,Any

class QueryRequest(BaseModel):
    question: str = Field(...,max_length=500,description="User Question to Query the document")
    top_k: int = Field(default=3,description="Number of chunks to retrive from vectore databases")

class SourceDocument(BaseModel):
    content: str = Field(...,description="Context of the document")
    metadata: Dict[str,Any] = Field(...,description="Context retrive from page and other details")
    similarity_score: float = Field(...,description="How much relative the query and topK")

class IngestResponse(BaseModel):
    status: str = Field(...,description="File upload status")
    chunks_created: int = Field(...,description="Chunks count based on document")
    document_ids: List[str] = Field(...,description="Docuemnts count")

class QueryResponse(BaseModel):
    answer: str = Field(...,description="Answer generated by LLM")
    sources : List[SourceDocument]= Field(...,description="Source file,page and other details")
    latency_ms : float

class HealthResponse(BaseModel):
    status: str = Field(...,description="Health Status")
    model_used: str = Field(default="llama-3.1-70b-versatile")
    environment: str = Field(...,description="Environmental details")
    version: str = Field(...,description=" App Version")
